# Конфигурация для получения подсетей
bgp_tools_url: "https://bgp.tools/table.txt"
user_agent: "Mozilla/5.0 (compatible; SubnetFetcher/1.0)"

# Директории для хранения файлов
ipv6_dir: "ipv6"
ipv4_dir: "ipv4"
RouterOSDir: "RouterOS"

# Настройки генерации конфигов для разных версий RouterOS
generate_v6: true  # Генерировать конфиги для RouterOS v6
generate_v7: true  # Генерировать конфиги для RouterOS v7

# Единый шлюз для всех маршрутов
gateway: "127.0.0.1"

# Предопределенные AS номера
as_numbers:
  "AS15169":  # Google
    file: "google.lst"
    list_name: "GOOGLE"
    comment: "Google networks"
  "AS32934":  # Facebook
    file: "facebook.lst"
    list_name: "FACEBOOK"
    comment: "Facebook networks"
  "AS8075":   # Microsoft
    file: "microsoft.lst"
    list_name: "MICROSOFT"
    comment: "Microsoft networks"

# Настройки Discord
discord:
  voice_v4: "https://iplist.opencck.org/?format=text&data=cidr4&site=discord.gg&site=discord.media"
  voice_v6: "https://iplist.opencck.org/?format=text&data=cidr6&site=discord.gg&site=discord.media"
  file: "discord.lst"
  list_name: "DISCORD"

# Настройки Telegram
telegram:
  cidr_url: "https://core.telegram.org/resources/cidr.txt"
  file: "telegram.lst"
  list_name: "TELEGRAM"

# Настройки Cloudflare
cloudflare:
  v4: "https://www.cloudflare.com/ips-v4"
  v6: "https://www.cloudflare.com/ips-v6"
  file: "cloudflare.lst"
  list_name: "CLOUDFLARE"
